/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lucas
 */
public class MenuRanking extends javax.swing.JFrame {

        Ranking rank;
        
        public MenuRanking() {
                rank = new Ranking();
                initComponents();
                initComponents2();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                jLabel10 = new javax.swing.JLabel();
                jLabelRankingNumbers = new javax.swing.JLabel();
                jLabelRankingImage = new javax.swing.JLabel();
                jLabelBackground = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Ranking");
                setBackground(new java.awt.Color(1, 50, 67));
                setForeground(new java.awt.Color(1, 50, 67));
                setMaximumSize(new java.awt.Dimension(400, 500));
                setMinimumSize(new java.awt.Dimension(400, 500));
                setPreferredSize(new java.awt.Dimension(400, 500));
                setResizable(false);
                getContentPane().setLayout(null);

                jLabel1.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(240, 52, 52));
                getContentPane().add(jLabel1);
                jLabel1.setBounds(120, 90, 240, 40);

                jLabel2.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(240, 52, 52));
                getContentPane().add(jLabel2);
                jLabel2.setBounds(120, 140, 240, 40);

                jLabel3.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(240, 52, 52));
                getContentPane().add(jLabel3);
                jLabel3.setBounds(120, 180, 240, 40);

                jLabel4.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(240, 52, 52));
                getContentPane().add(jLabel4);
                jLabel4.setBounds(120, 210, 240, 40);

                jLabel5.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(240, 52, 52));
                getContentPane().add(jLabel5);
                jLabel5.setBounds(120, 250, 240, 40);

                jLabel6.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(240, 52, 52));
                getContentPane().add(jLabel6);
                jLabel6.setBounds(120, 290, 240, 40);

                jLabel7.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
                jLabel7.setForeground(new java.awt.Color(240, 52, 52));
                getContentPane().add(jLabel7);
                jLabel7.setBounds(120, 330, 240, 40);

                jLabel8.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
                jLabel8.setForeground(new java.awt.Color(240, 52, 52));
                getContentPane().add(jLabel8);
                jLabel8.setBounds(120, 370, 240, 40);

                jLabel9.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
                jLabel9.setForeground(new java.awt.Color(240, 52, 52));
                getContentPane().add(jLabel9);
                jLabel9.setBounds(120, 410, 240, 40);

                jLabel10.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
                jLabel10.setForeground(new java.awt.Color(240, 52, 52));
                getContentPane().add(jLabel10);
                jLabel10.setBounds(120, 440, 240, 40);

                jLabelRankingNumbers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Numeros_Rank.png"))); // NOI18N
                getContentPane().add(jLabelRankingNumbers);
                jLabelRankingNumbers.setBounds(0, 80, 110, 410);

                jLabelRankingImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo_Ranking1.png"))); // NOI18N
                getContentPane().add(jLabelRankingImage);
                jLabelRankingImage.setBounds(100, 30, 210, 50);

                jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Blue_background.jpg"))); // NOI18N
                getContentPane().add(jLabelBackground);
                jLabelBackground.setBounds(0, 0, 400, 501);

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        public void initComponents2(){
                String[] finalRank = new String[10];
                
                for (int i = 0; i < 10; i++){
                        String labelString = new String();
                        labelString = (rank.getNamesTop10(i));
                
                        int nameLength = labelString.length();
                        for (int k = 0; k < 15-nameLength; k++){
                                labelString += " ";
                        }
                
                        labelString += (Integer.toString(rank.getScoresTop10(i)));
                        
                        finalRank[i] = labelString;
                }
                
                jLabel1.setText(finalRank[0]);
                jLabel2.setText(finalRank[1]);
                jLabel3.setText(finalRank[2]);
                jLabel4.setText(finalRank[3]);
                jLabel5.setText(finalRank[4]);
                jLabel6.setText(finalRank[5]);
                jLabel7.setText(finalRank[6]);
                jLabel8.setText(finalRank[7]);
                jLabel9.setText(finalRank[8]);
                jLabel10.setText(finalRank[9]);
                
                
                jLabel10.setText(rank.getNamesTop10(0));
                
                //for(User xUser: users){
                //                if (count < 10){
                //                        int nameLength = xUser.topUserName.length();
                //                        pw.print(xUser.topUserName + " "); 
                //                        for (int i = 0; i < 21-(nameLength+1); i++){
                //                                pw.print("-");
                //                        }
                //                        pw.println(xUser.topUserScore);
                //                }
                //        count++;
                //}
        }
        
        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(MenuRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(MenuRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(MenuRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(MenuRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new MenuRanking().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JLabel jLabelBackground;
        private javax.swing.JLabel jLabelRankingImage;
        private javax.swing.JLabel jLabelRankingNumbers;
        // End of variables declaration//GEN-END:variables
}
